### ISSUE TITLE
Check expiration date in the case of an invalid signature

### ISSUE THREAD

**Issue by wgwz** [pallets/itsdangerous#123]
Is it or could it be possible to check the expiration date in the case of an invalid signature? I think the relevant code is [here][1]. I think the answer is no but I'm curious if it is possible.

[1]: https://github.com/pallets/itsdangerous/blob/master/src/itsdangerous/timed.py#L118-L147

**Comment by davidism** [comment]
https://github.com/pallets/itsdangerous/blob/master/src/itsdangerous/timed.py#L44 You can extract the timestamp from the data (assuming it's even there and valid, since the signature failed) in the same way `TimestampSigner` does: https://github.com/pallets/itsdangerous/blob/master/src/itsdangerous/timed.py#L69-L71, but that's not exposed by itsdangerous directly.

**Comment by wgwz** [comment]
would you be open to exposing this lines of code in separate method @davidism? https://github.com/pallets/itsdangerous/blob/master/src/itsdangerous/timed.py#L51-L73

**Comment by wgwz** [comment]
it looks i might be able to access what i need in the exception. so possibly nevermind.
