### ISSUE TITLE
TimestampSigner writes local-time timestamps and reads them as UTC

### ISSUE THREAD

**Issue by taleinat** [pallets/itsdangerous#137]
`TimestampSigner` uses `int(time.time())` to create timestamps, which will use the local timezone. However, it uses `datetime.utcfromtimestamp` to convert them into datetime objects, which will create naive `datetime` objects by interpreting the timestamp in the UTC timezone.

The fix should be to always write UTC timestamps. See [this StackOverflow question](https://stackoverflow.com/questions/5067218/get-utc-timestamp-in-python-with-datetime) for examples how to do this properly.

To be clear, this is in reference to [this current code](https://github.com/pallets/itsdangerous/blob/ea267c1d3b16cf1fffd3c21d0ea174fc8bcbe73c/src/itsdangerous/timed.py#L24):
```python
    def get_timestamp(self):
        """Returns the current timestamp. The function must return an
        integer.
        """
        return int(time.time())

    def timestamp_to_datetime(self, ts):
        """Used to convert the timestamp from :meth:`get_timestamp` into
        a datetime object.
        """
        return datetime.utcfromtimestamp(ts)
```

**Comment by davidism** [comment]
You appear to be right, but this code has always been this way for *8 years*, and yet no one has ever reported that their tokens last hours longer than they should, or are instantly invalid. How did this slip by?

**Comment by davidism** [comment]
I guess an explanation for my projects specifically is that I always deploy it on a server using UTC time, which should be the most common setup by far.

**Comment by taleinat** [comment]
> You appear to be right, but this code has always been this way for 8 years, and yet no one has ever reported that their tokens last hours longer than they should, or are instantly invalid. How did this slip by?

The expiration check compares timestamps directly, and they are generated by the same `self.get_timestamp()` call, so it is always compares local timestamps to each other. The conversion to datetime objects appears to only directly be used for the SignatureExpired exceptions and when returning the timestamp, which may rarely be used in a way that this effect would be noticed.

Still, not using UTC timestamps could cause issues e.g. due to daylight saving time changes, trying to host servers in multiple timezones, local development vs. production, etc.

**Comment by LeonardoFurtado** [comment]
Can I try to solve this?

**Comment by taleinat** [comment]
@LeonardoFurtado, considering the "good-first-issue" label added to this, I assume that would be most welcome.

Regardless, nobody is going to stop you from creating a PR...

**Comment by pganssle** [comment]
> `TimestampSigner` uses `int(time.time())` to create timestamps, which will use the local timezone.

I mentioned something along these lines in #148, but this is not really accurate. `time.time()` gives you "number of seconds since the epoch", which is independent of time zone - it is the number of seconds that have elapsed since 1970-01-01T00:00 UTC. The number will not change if you change your time zone:

```
$ cat >print_time.py << EOF
> from datetime import datetime
> import time
> print(datetime.now())
> print(time.time())
> EOF
$ TZ="UTC" python print_time.py
2020-04-15 01:44:49.408191
1586915089.4082322
$ TZ="America/New_York" python print_time.py
2020-04-14 21:44:56.964520
1586915096.9645472
$ TZ="America/Los_Angeles" python print_time.py
2020-04-14 18:45:02.063382
1586915102.0634115
```

If there's a problem here, it's [the use of `datetime.utcfromtimestamp(ts)`](https://blog.ganssle.io/articles/2019/11/utcnow.html), which should be replaced with `datetime.fromtimestamp(ts, tz=UTC)`. If the results of `timestamp_to_datetime` are only ever compared to other results from `timestamp_to_datetime`, then this will always do the right thing, regardless of which one you use (though in the article I argue that you should still not use `utcfromtimestamp`). The kinds of bugs you'd likely see would be of the form where someone does `timestamp_to_datetime(ts).timestamp()` which would erroneously return a value other than `ts`. Explicitly returning a UTC datetime in `timestamp_to_datetime` fixes that problem.

**Comment by davidism** [comment]
The only thing we're doing with the timestamps is subtracting the current timestamp int from the one when the signature was created, to figure out if the age is greater than the max age.

I want to be careful to call out if changing this will potentially make some timestamps invalid a few hours early or late because of timezones. It sounds like there shouldn't be any affect besides internal correctness, does that seem right?

**Comment by pganssle** [comment]
> I want to be careful to call out if changing this will potentially make some timestamps invalid a few hours early or late because of timezones. It sounds like there shouldn't be any affect besides internal correctness, does that seem right?

It depends on what you mean by "changing this". I would not recommend changing from `int(time.time())` to something like `datetime.now(UTC).timestamp()`, because the two do the same thing, except the second one is slower.

If you want to change `timestamp_to_datetime` to return an aware datetime - which is *something* of a correctness issue (though possibly more of a non-intuitive user interface issue) - the big question is whether you  consider `unsign` and `timestamp_to_datetime` to be public interfaces, and if so whether you're willing to make potentially backwards-incompatible changes to them. Both of them [are documented](https://itsdangerous.palletsprojects.com/en/1.1.x/timed/), and `unsign` takes a `return_timestamp` argument that explicitly is documented as returning a naive datetime:

> If `return_timestamp` is `True` the timestamp of the signature will be returned as a naive `datetime.datetime` object in UTC.

I believe the most likely thing to break if you change it to return an aware UTC time zone would be if people are doing things like arithmetic or comparisons between the result of `timestamp_to_datetime` or `unsign` and some naive datetimes they generate by some other mechanism - which would start raising an error.

**Comment by davidism** [comment]
@pganssle Thanks for your help. Since the next version will be a major bump, I think it will be better long term to start returning aware values. These methods are mainly used internally, returning the timestamp seems mostly informational.

Closing, I'll open a new issue about returning timezone-aware values.
