### ISSUE TITLE
limit chars count

### ISSUE THREAD

**Issue by alirezaimi** [pallets/itsdangerous#142]
Hi
is there any way that set max on chars count ?

```
auth_s = URLSafeSerializer("XXX", "auth")
pay_desc_ec = auth_s.dumps({"a": "honnuedjjy251", "b": 288647978114144616553751029061706329932})

pay_desc_ec : eyJwYXlfc2VjdGlvbiI6ImhvbmV5c2VsbGJvdCIsImNhcnRfY29kZSI6IjI4ODY0Nzk3ODExNDE0NDYxNjU1Mzc1MTAyOTA2MTcwNsMyOTkzMiJ9.D-0WTmpxZpwTFjTVkNA6NQ5PDoA
```

140 chars for encoded !!!!

**Comment by ThiefMaster** [comment]
No, how do you expect that to work? The encoded string needs to contain your data and the signature, and since you want it to be URL-safe, it's base64-encoded which makes it longer. You have 67 chars of plain data, and 92 when base64 encoding them. The full result from dumps() is 115 chars long...

Your 140 chars long string clearly has more data btw:

```
>>> s = 'eyJwYXlfc2VjdGlvbiI6ImhvbmV5c2VsbGJvdCIsImNhcnRfY29kZSI6IjI4ODY0Nzk3ODExNDE0NDYxNjU1Mzc1MTAyOTA2MTcwNsMyOTkzMiJ9.D-0WTmpxZpwTFjTVkNA6NQ5PDoA'

>>> b64decode(s.split('.')[0])
b'{"pay_section":"honeysellbot","cart_code":"288647978114144616553751029061706\xc329932"}'
```
