### ISSUE TITLE
SHA1 should no longer be the default digest method.

### ISSUE THREAD

**Issue by GrayHatter** [pallets/itsdangerous#145]
Given that SHA1 was broken again, it's use as a default digest method should be reconsidered. I agree with the previous consensus that HMAC-SHA1 is still probably secure. But without a doubt HMAC-SHA512 is more secure. 

It's also more computationally expensive, of course. But IMHO the default should be to be as secure as possible, with the option to prefer performance left to the user. (Who hopefully would make the correct decision for them.) That way any user who wants to implement something secure can do so without the crypto background needed, just by using the defaults; where users who have the background can use the custom configuration they would have used anyways.

**Comment by davidism** [comment]
I can't find the previous discussion(s) right now, but the use of SHA1 in ItsDangerous is not an issue here. It is using SHA1 as an intermediate step for PBKDF2. Used in this way, SHA1 (and even MD5) are not vulnerable in the way outlined by the attacks.

**Comment by ThiefMaster** [comment]
I think if we want to change the default (either here or in Flask) we should certainly allow SHA1 as a fallback so existing sessions are not invalidated by default. That said, the currently exposed API on Flask's session interface does not allow setting the fallback methods (which I think itsdangerous supports since 1.1), so adding that would probably be a good idea to make it easier for people to switch algorithms even if they want to preserve existing sessions for a while...
