### ISSUE TITLE
Allow timedelta as argument to TimestampSigner.unsign

### ISSUE THREAD

**Issue by septatrix** [pallets/itsdangerous#185]
This makes it easier to allow a higher `max_age` without having to calculate the seconds from e.g. 30 minutes or 5 hours. If no one is going to oppose this I would like to implement this.

**Comment by davidism** [comment]
I know accepting int/float or timedelta is fairly common in other parts of Pallets, but over time I've become less convinced it's a good idea. Accepting multiple types makes typing signatures less clear, and seems to go against Python's general move towards having the developer be aware of the type of data they're passing (str vs int, etc.). Internally, `unsign` works with numeric timestamps, not datetime objects, so I think it makes sense to accept a numeric value here. If you want to use a timedelta, instead of `unsign(td)`, call `unsign(td.total_seconds())`.

**Comment by septatrix** [comment]
Okay I see your argument however I do not think mixing `int` and `timedelta` is bad in this case. Internally they are very closely related and not completely different data structures like `list` and `dict`. Furthermore does `unsign` return a `datetime.timestamp` and also raise one should there be an error. Always having to call `dt.total_seconds()` also does not feel like idiomatic Python

**Comment by davidism** [comment]
> Internally they are very closely related

I guess kinda, in that a timedelta stores a bunch of numbers?

> Always having to call `dt.total_seconds()` also does not feel like idiomatic Python

That's something you'll have to reconcile on your own, calling methods on objects is about as fundamental as you can get. If your project really wants to pass timedeltas to itsdangerous objects, and you don't want to call `total_seconds`, subclass:

```python
class MySigner(TimestampSigner):
    def unsign(..., max_age=None):
        if isinstance(max_age, timedelta):
            max_age = max_age.total_seconds()
        return super().unsign(..., max_age=max_age)
```

**Comment by septatrix** [comment]
> I guess kinda, in that a timedelta stores a bunch of numbers?

Yes, timedelta consists of only hours, seconds and microseconds.

Creating a subclass (or a few more for the variants) seems overkill but I guess this is what we will have to do then

<hr>

> Internally, unsign works with numeric timestamps, not datetime objects, so I think it makes sense to accept a numeric value here.

Regardless of allowing timedelta as a parameter: After looking at the code it seems like using a datetime object directly would actually get rid of multiple conversions.
