### ISSUE TITLE
Incompatibility with Flask 1.1.1 (cannot import name 'json' from 'itsdangerous')

### ISSUE THREAD

**Issue by ThorstenEngel** [pallets/itsdangerous#290]
Hi,

using version 2.1.0 will let my flask (Flask==1.1.1) crash. Using 2.0.1 works as usual. Python 3.10., Alpine 3.15.

For me, this looks like a problem with itsdangerous, but I am unsure..

Warm regards,

thorsten

`Traceback (most recent call last):
mailsrv                      |   File "/src/app/main.py", line 14, in <module>
mailsrv                      |     from flask import send_from_directory
mailsrv                      |   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
mailsrv                      |     from . import json
mailsrv                      |   File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 15, in <module>
mailsrv                      |     from itsdangerous import json as _json
mailsrv                      | ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)`

**Comment by rcarpa** [comment]
It is clearly stated in the changelog : https://itsdangerous.palletsprojects.com/en/2.1.x/changes/ 
Probably a problem to report to flask developers, not here

**Comment by ThiefMaster** [comment]
The problem is that people don't pin all their dependencies. Use up to date flask and jinja versions, and you won't have problems with an up to date markupsafe version :)

Alternatively, you can pin your transitive dependencies and you won't have a problem either ;)

**Comment by davidism** [comment]
Duplicate of #289 

You are using an unsupported version of Flask, please update to the latest version. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.
