### ISSUE TITLE
Migration guide for deprecated JSONWebSignatureSerializer

### ISSUE THREAD

**Issue by jace** [pallets/itsdangerous#292]
The deprecated JWS functionality needs a migration guide for existing users.

My code broke today after pip-compile upgraded itsdangerous to 2.1.0. The changelog tells me to use authlib, but authlib's documentation offers multiple options. Since I need existing signatures to continue working while I figure out a migration, I've set my requirements file to `itsdangerous<2.1.0` for now.

It'll be nice to have a brief migration guide in the documentation.

**Comment by davidism** [comment]
We don't support JWS, so it seems a bit weird to have a guide to implementing JWS in our docs. I understand that it's complex, that's one of the reasons we don't support it. Perhaps the authors of Authlib, Flask-JWT-Extended, etc. would be interested in writing a guide in their docs, but I don't have the ability to write it since I don't use JWS.

**Comment by Colin-b** [comment]
It seems to be pretty straightforward is you use python-jose as a replacement: https://python-jose.readthedocs.io/en/latest/jws/index.html
