### ISSUE TITLE
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous'

### ISSUE THREAD

**Issue by ibraheemalayan** [pallets/itsdangerous#294]
Since I upgraded to **2.1.0** I keep getting the following error when I try to import `itsdangerous`

```
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous'
```

To replicate the bug just install those versions of the packages

the output of `flask --version`

```
Python 3.9.9
Flask 2.0.3
Werkzeug 2.0.3
```

the output of `pip3 show itsdangerous `

```
Name: itsdangerous
Version: 2.1.0
Summary: Safely pass data to untrusted environments and back.
Home-page: https://palletsprojects.com/p/itsdangerous/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /****************************_venv/lib/python3.9/site-packages
Requires:
Required-by: Flask, Flask-WTF
```

Environment:

- Python version: 3.9.9
- Flask version: 2.0.3
- ItsDangerous version: 2.1.0

**Comment by ibraheemalayan** [comment]
As a _**_temporary_**_ solution, just downgrade to the previous version 
```
pip3 install itsdangerous==2.0.1
```

**Comment by davidism** [comment]
This is intentional, we no longer support JWS. Use a dedicated library like [authlib](https://docs.authlib.org/en/latest/) or one of the various Flask extensions instead. The removal was listed in the changes for 2.1.0, and its deprecation was listed in 2.0.0: https://itsdangerous.palletsprojects.com/en/2.1.x/changes/#version-2-1-0.

A deprecation warning has been emitted since 2.0. Running tests with warnings treated as errors is recommended throughout the Python ecosystem (not just by Pallets) in order to see these changes early.

Additionally, pinning dependencies with a tool like [pip-tools](https://pypi.org/project/pip-tools/) or another project management tool is required (again throughout the Python ecosystem) in order for projects to control when they get updates.
