### ISSUE TITLE
is there an interface to extend the token expiry time of an issued token?

### ISSUE THREAD

**Issue by saiparty** [pallets/itsdangerous#45]
if the token is about to expire, I want to call an interface (or any one can point me in correct way) to extend the expiry time of an already issued token. I am using TimedJSONWebSignatureSerializer to create the tokens.

**Comment by Metalgrid** [comment]
It's impossible to provide a facility like that because the expiration time is in the token itself. When you change any value in the token, you get a completely different token. An alternative implementation would be to issue a refresh token that won't expire and use that to issue new primary tokens.
