### ISSUE TITLE
`TimestampSigner` not working as expected when I use a `-` as separator 

### ISSUE THREAD

**Issue by avinassh** [pallets/itsdangerous#62]
To produce the error: 

```
from itsdangerous import TimestampSigner
s = TimestampSigner('secret-key', sep='-')
string = s.sign('foo')
s.unsign(string, max_age=50)
```

When I ran the above code multiple times in loop, I got following exceptions: `SignatureExpired` or `BadTimeSignature`.

**Comment by davidism** [comment]
I can't reproduce either error with the example given.  If you got a signature expired, then you waited longer than 50 seconds before unsigning.

**Comment by avinassh** [comment]
Nope, I am not waiting more than 50 seconds, I am just checking instantly. Here is an video demo where I am just copy pasting repeatedly and you will see both the errors: http://gifyu.com/image/FHN

**Comment by davidism** [comment]
I can't view that gif, and it wouldn't help anyway.  Please include a reproducible example.

**Comment by avinassh** [comment]
I used the same code which I had posted earlier. Now I am not sure why its not generating error in your machine.

**Comment by johnlam** [comment]
Here's what I think is going on.
The signature will be  [urlsafe_b64encode()](https://docs.python.org/2/library/base64.html#base64.urlsafe_b64encode)d .
So part of the signature (and/or part of the timestamp) *might* contain your separator `-` , which would result in either a wrong timestamp or a wrong signature.

A potential fix could be to check if the separator is part of the base64_urlsafe() charset and/or write that in the docs.

How to reproduce.
````python
for i in xrange(100):
    s = TimestampSigner('secret-key',sep='-')
    mystr = s.sign('foo')
    try:
        s.unsign(mystr,max_age=200)
    except:
        raise
    time.sleep(1)
```

Example string foo-CmVi_g-pt8iji6JAw61H0EJm-bFJumhEZw (signature will be `bFJumhEZw` instead of `pt8iji6JAw61H0EJm-bFJumhEZw`)

**Comment by untitaker** [comment]
I fixed it exactly as @johnlam described. I'm not considering this API breakage because this sort of usage never worked.
