### ISSUE TITLE
Timestamps: monotonic and higher resolution?

### ISSUE THREAD

**Issue by c4milo** [pallets/itsdangerous#97]
Thanks for itsdangerous! It has been a very helpful package thus far. We are currently using it to sign and timestamp one-time tokens and were wondering if adding a lower time resolution as well as monotonic time will help to reduce the risk of token replay attacks and skewed clocks.  Thanks!

**Comment by c4milo** [comment]
Thanks for the quick reply @ThiefMaster! 

I'm not sure I'm following. Even reducing max_age, the timestamp resolution is still the same: seconds. This means that if I receive two or more requests within one second, the token will allow, say, updating a password twice.

**Comment by ThiefMaster** [comment]
You need to keep track of already-used tokens for the remainder of their lifetime if you want them to be usable only once.

Even if there was below-second granularity - how would this work e.g. for a password reset token? Do you expect your user to use the token within less than a second?

**Comment by c4milo** [comment]
> Do you expect your user to use the token within less than a second?
no, I would expect an attacker to do that, hijack the token and send it again changing the password to some other value. 1 second isn't an unreasonable window. 1 millisecond is.

**Comment by c4milo** [comment]
I'm closing since my original question was answered. Thanks @ThiefMaster!

**Comment by ThiefMaster** [comment]
I think you still misunderstand how itsdangerous works. `max_age` is not the time between the first use until it expires. It's the time since creation. So if you have a token valid for 1 second, your user would have to use it within a second of you creating it. Unless your user is a program AND has a good connection with low latency, the token will already be expired once he sends it back to you.
